runtime: nodejs20
instance_class: F1
env: standard
env_variables:
  MONGO_URI: "your-mongo-uri"
  PORT: "8080" 
handlers:
  - url: /.*  
    script: auto
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "./notify-firebase-key.json"
